frontend/src/views/real/SearchDeparturePage.vue, frontend/src/views/real/SearchDestinationPage.vue
카카오 키워드 장소 검색 REST API 보안키 .env로 이동
- api 보안 키 직접 하드코딩 했던거 .env로 이동하고 VUE_APP_KAKAO_REST_KEY 로 수정
- 내용을 적어주세요.
=> Feat: 카카오 키워드 장소 검색 REST API 보안키 .env로 이동

frontend/src/views/joohan-test/test.txt
실시간, 예측 분기 로직 테스트 폴더 작성
- 실시간이면 api를 받아와서 5005번(예시)을 타는 정류장의 첫번째 도착 예정 버스의 여석을 받아오고, 실시간이 아니면 mysql을 aws rds로 불러와서 예측 여석 받아옴
- 일단 그 전이 없으니까 개발할때는 연습으로 임의로 5005번을 탈 수 있는 하나의 정류장을 잡아서 (정류장명, 정류장코드, 정류장 x,y좌표 등)을 넘겨받아서 실시간이면 if문으로 오디세이 실시간 버스 도착정보에 넘기고 거기서 여석 정보 받아오기, 아니면 aws rds의 파라미터 정보 받아오기(영균님이 주신 예시자료 참고)
- 내용을 적어주세요.
=> Feat: 실시간, 예측 분기 로직 테스트 폴더 작성

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/real/BusSearchPage.vue
경로별 모든 5000A와 5000B가 중복 출력되는 부분 수정 예정
Fix: 버스 검색 결과에서 하나의 노선만 받아오는 오류 수정
- 길찾기 돌리는 부분에서 하나의 노선으로만 계속 연결되는 오류 수정 및 searchcomponent 로그 추가
- 동일 노선 중복 출력 오류 수정
=> Fix: 버스 검색 결과에서 하나의 노선만 받아오는 오류 수정

frontend/src/App.vue, frontend/src/views/MapTestPage/RouteSearchResultView.vue, frontend/src/views/real/BusSearchPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Design: 검색 결과 페이지 및 길찾기 페이지 모바일 웹페이지 형태로 디자인

.vscode/extensions.json, frontend/src/views/real/BusSearchPage.vue, frontend/src/views/real/LoadingOverlay.vue
로딩화면 기본 함수 배치 및 틀 구현
- 로딩 오버레이 뷰 작성
- .vscode 폴더 생성
- 내용을 적어주세요.
- #8
- 로딩 오버레이뷰를 버스 결과 페이지에 임포트해서 거기서 추가적인 계산 db -> 푸아송 -> 길찾기 -> 정렬 진행하는 중에 이거 뜨도록 함수 넣어야함
=> Feat: 로딩화면 기본 함수 배치 및 틀 구현

frontend/src/store/modules/departure.js, frontend/src/store/modules/destination.js, frontend/src/store/modules/time.js
서버 처음 실행시에만 vuex 초기화되도록 수정
- departure.js
- destination.js
- time.js
vuex 모듈에 각각 initialize 초기화 플래그 및 초기화 mutation 추가
- 내용을 적어주세요.
- 이슈 번호: #7 
=> Fix #3: 서버 처음 실행시에만 vuex 초기화되도록 수정

frontend/package-lock.json, frontend/package.json, frontend/proxyServer.js, frontend/src/components/layout/SearchFormComponent.vue, frontend/src/router/index.js, frontend/src/views/real/BusSearchPage.vue, frontend/src/views/real/MainPage.vue, frontend/src/views/real/MapComponent.vue, frontend/src/views/real/gonggong.vue, frontend/vue.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 디자인 수정 및 서울버스도착정보 받아오는 파일 작성

frontend/src/views/joohan-test/index.html, frontend/src/views/joohan-test/script.js, frontend/src/views/joohan-test/test.txt
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> ADD: 실시간, 예측 분기 로직 테스트

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/real/BusSearchPage.vue, frontend/src/views/real/MainPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Design: 디자인 일부 수정 및 공공데이터포탈 api 컴포넌트 틀 작성

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/router/index.js, frontend/src/views/real/MainPage.vue, frontend/src/views/real/SearchDeparturePage.vue, frontend/src/views/real/SearchDestinationPage.vue
지도 관련 기본 기능 구현
- 메인 페이지
- 출발지, 도착지 검색 페이지
- 내용을 적어주세요.
- 이슈 번호: #8 
=> Feat: 지도 관련 기본 기능 구현

frontend/src/views/real/SearchDeparturePage.vue, frontend/src/views/real/SearchDestinationPage.vue
즐겨찾기 기능 구현
- 출/도착지 페이지 즐겨찾기 기능 구현
- 내용을 적어주세요.
- 이슈 번호: #18 
=> Feat: 즐겨찾기 기능 구현

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/real/MainPage.vue, frontend/src/views/real/SearchDeparturePage.vue, frontend/src/views/real/SearchDestinationPage.vue
메인페이지 및 출/도착지 검색 페이지 세부 기능 구현 및 오류 수정
- 출/도착지 입력란 옆 삭제 버튼 구현
- 출/도착지 검색 결과 페이지 지도 및 라우터 오류 수정
- 메인 페이지 슬라이딩 메뉴 추가
- 내용을 적어주세요.
- 이슈 번호: #8 
=> Feat: 메인페이지 및 출/도착지 검색 페이지 세부 기능 구현 및 오류 수정

frontend/src/components/layout/SearchFormComponent.vue
메인 페이지 시간 설정 버그 해결
- 설정 버튼을 눌러야 시간이 변경되도록 vuex 로직 수정
- 닫기 버튼 누르면 그대로 유지
- 내용을 적어주세요.
=> Fix: 메인 페이지 시간 설정 버그 해결

frontend/src/views/real/BusDetailInfo.vue, frontend/src/views/real/test.js, frontend/tailwind.config.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 결과 페이지 테스트 로직 구

frontend/src/views/real/BusDetailInfo.vue
내용을 적어주세요.
- 이런식으로 모든 정류장의 좌석 받아올 수 있음
- 내용을 적어주세요.
=> Feat: 실시간 좌석 받아오는 기능 구현

frontend/src/router/index.js, frontend/src/views/real/BusDetailLocation.vue
버스 위치정보 및 상세 정보 화면에 표시하는 기능 구현
- 오디세이 버스 노선조회 api
- 오디세이 버스 상세노선 조회 api
- 공공데이터포탈 경기도_버스위치정보 조회 api
넘겨주는 로직만 작성하면 됨
- 내용을 적어주세요.
- 락걸릴까봐 좀 불안함
=> Feat: 버스 위치정보 및 상세 정보 화면에 표시하는 기능 구현

frontend/src/views/real/BusDetailLocation.vue, frontend/src/views/real/SearchDeparturePage.vue
Feat: 장소 검색 페이지 오디세이 정류장 api 추가
- 검색 결과에 역이 안뜨는 문제가 있어서 정류장 추가함
- 도착지에도 추후 추가해야함
- 내용을 적어주세요.
- 이슈 번호: #8
=> Feat: 장소 검색 페이지 오디세이 정류장 api 추가

frontend/src/views/real/po.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 버스 노선 정보에 따라 포아송 분포로 넘기는 코드 작성(테스트 해야함)

frontend/src/views/real/po.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Style: 로직 작성 틀 주석 추가

frontend/src/router/index.js, frontend/src/views/real/test/Debugging.vue
/debugging
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: csv api 분기 로직 작성

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/real/BusSearchPage.vue, frontend/src/views/real/test/FinalPage.vue, frontend/src/views/real/test/busData.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 정류장 로딩 로직까지

frontend/src/views/real/test/FinalPage.vue, frontend/src/views/real/test/busArrivalAPI.js, frontend/src/views/real/test/busData.js, frontend/src/views/real/test/seatCalculation.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 실시간 api 불러오기 및 10분 내 여석 합치는 로직 추가

frontend/src/views/real/test/FinalPage.vue, frontend/src/views/real/test/busArrivalAPI.js, frontend/src/views/real/test/busData.js, frontend/src/views/real/test/csvLoader.js, frontend/src/views/real/test/poisson.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 로직 연결 오류 수정 중(seq 맞추기)

frontend/src/router/index.js, frontend/src/store/modules/route.js, frontend/src/views/real/NoFinalPage.vue, frontend/src/views/real/PathDetailPage.vue, frontend/src/views/real/PathfindingPage.vue, frontend/src/views/real/test/FinalPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 길찾기 결과 페이지 연동 코드 작성

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/router/index.js, frontend/src/views/real/MainPage.vue, frontend/src/views/real/test/FinalPage.vue, frontend/src/views/real/test/ResultPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 확률 결과 페이지 수정

frontend/package-lock.json, frontend/package.json, frontend/src/components/layout/SearchFormComponent.vue, frontend/src/router/index.js, frontend/src/views/real/MainPage.vue, frontend/src/views/real/PathDetailPage.vue, frontend/src/views/real/PathfindingPage.vue, frontend/src/views/real/RouteBar.vue, frontend/src/views/real/SearchDeparturePage.vue, frontend/src/views/real/SearchDestinationPage.vue, frontend/src/views/real/test/ResultPage.vue
기능 연결 예정
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 전체적인 디자인 수정 및 기능 추가

frontend/src/router/index.js, frontend/src/views/real/BusDetailLocation.vue, frontend/src/views/real/MainPage.vue, frontend/src/views/real/PathDetailPage.vue, frontend/src/views/real/test/ResultPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 노선 정보 페이지 추가

LISENCE, frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/NoBusPathPage/NoBusPathDetailPage.vue, frontend/src/views/NoBusPathPage/NoBusPathfindingPage.vue, frontend/src/views/PathPage/PathDetailPage.vue, frontend/src/views/PathPage/PathfindingPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix: 아이콘 오류 수정

frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/busArrivalAPI.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> !HOTFIX: 실시간 버스 여석 받아오는 파라미터 오류 수정

frontend/src/views/ResultPage/realpoisson.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Add: 디버깅용 로그 추가(cumulativeProb)

frontend/src/views/NoBusPathPage/NoBusPathfindingPage.vue, frontend/src/views/PathPage/PathfindingPage.vue, frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/realpoisson.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat #56: 결과 페이지 전체적인 api 호출 및 함수 구현 마무리

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/ResultPage/ResultPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat: 정류장별 소요시간 및 도착지 경로, 실시간 버튼 수정

frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/busArrivalAPI.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> !HOTFIX #63: 정류장 받아올 때 네이버 지도와 같은 정류장으로부터 상위 4개 받아오지 않는 오류 수정

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/views/Mainpage/MainPage.vue, frontend/src/views/NoBusPathPage/NoBusPathDetailPage.vue, frontend/src/views/PathPage/PathDetailPage.vue, frontend/src/views/PathPage/PathfindingPage.vue, frontend/src/views/ResultPage/Result.css, frontend/src/views/ResultPage/ResultPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat #63: 메인 페이지 및 지도 수정

frontend/src/views/NoBusPathPage/NoBusPathDetailPage.vue, frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/busApi.js
가끔 api 결과 자체에서 다른 경우는 어쩔 수 없음
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix #63: 정류장 네이버 지도와 같게 출력하도록 변경

frontend/src/views/ResultPage/Result.css, frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/busArrivalAPI.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Feat #63: 논의 후 생긴 여러 수정사항 반영

frontend/src/utils/RouteBar.vue, frontend/src/views/NoBusPathPage/NoBusPathDetailPage.vue, frontend/src/views/NoBusPathPage/NoBusPathFinding.css, frontend/src/views/NoBusPathPage/NoBusPathfindingPage.vue, frontend/src/views/NoBusPathPage/RouteBar.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix #63: 버스 노선 없을 때 길찾기 제공 페이지 오류 수정

frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/ResultPage/busArrivalAPI.js
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix #63: csv 분기 로직 최종 수정(테스트 완료)

frontend/src/store/modules/search.js, frontend/src/store/modules/station.js, frontend/src/views/BusDetailPage/BusDetailLocation.vue, frontend/src/views/Mainpage/Footer.vue, frontend/src/views/NoBusPathPage/NoBusPathfindingPage.vue, frontend/src/views/PathPage/PathfindingPage.vue, frontend/src/views/ResultPage/Result.css, frontend/src/views/ResultPage/ResultPage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix: 디자인 오류 수정 및 로직 보강

frontend/src/components/layout/SearchFormComponent.vue, frontend/src/components/layout/SearchFormStyle.css, frontend/src/views/BusDetailPage/BusDetailLocation.vue, frontend/src/views/Mainpage/Footer.vue, frontend/src/views/Mainpage/MainPage.vue, frontend/src/views/NoBusPathPage/NoBusPathFinding.css, frontend/src/views/NoBusPathPage/RouteBar.vue, frontend/src/views/PathPage/PathDetailPage.vue, frontend/src/views/PathPage/PathfindingPage.vue, frontend/src/views/PathPage/RouteBar.vue, frontend/src/views/ResultPage/Result.css, frontend/src/views/ResultPage/ResultPage.vue, frontend/src/views/SearchPage/SearchDeparturePage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Style: 코드 정리

frontend/src/views/SearchPage/SearchDeparturePage.vue
내용을 적어주세요.
- 내용을 적어주세요.
- 내용을 적어주세요.
=> Fix: 검색하기 렌더링 안겹치게 수정
